global using System.Linq.Expressions;
global using Ater.Web.Abstracture.Interface;
global using Ater.Web.Core.Models;
global using Ater.Web.Core.Utils;
global using Entity;
global using EntityFramework.CommandStore;
global using EntityFramework.QueryStore;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Logging;
